spring.application.name=notification-service
server.port=8088

# External services
services.user.url=${SERVICES_USER_URL:http://user-service:8083}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu03673@gmail.com
spring.mail.password=flru ykou mcmg fvbg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true